# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-22 02:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0004_auto_20171221_1739'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wish',
            new_name='ItemWish',
        ),
    ]
