# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-22 03:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0005_auto_20171221_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemwish',
            name='created_by',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items_added', to='wishlist.User'),
        ),
        migrations.AlterField(
            model_name='itemwish',
            name='wishlist',
            field=models.ManyToManyField(default='', null=True, related_name='wishes', to='wishlist.User'),
        ),
    ]
