# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-22 04:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0006_auto_20171221_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hireddate',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
