# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-22 21:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0007_auto_20171221_2012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemwish',
            old_name='wishlist',
            new_name='wished_by',
        ),
    ]
