# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-22 21:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0008_auto_20171222_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemwish',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_added', to='wishlist.User'),
        ),
        migrations.AlterField(
            model_name='itemwish',
            name='wished_by',
            field=models.ManyToManyField(related_name='wishes', to='wishlist.User'),
        ),
    ]
